### PR TITLE
Julia implementation using Pluto.jl notebooks

### PR DESCRIPTION
**Pull request by stefanbringuier**
I was curious if there is any interest in merging the [Julia](https://julialang.org/) [Pluto.jl notebooks](https://github.com/fonsp/Pluto.jl) I've been working on which replicate the python based Jupyter notebooks for this tutorial.

The purpose is to show how a practitioner could implement the same workflows using Julia based packages. The purpose of using Pluto notebooks is just for possible additional flexibility.

At the moment I have worked through tutorials 1-3 and the Julia implementation shows good agreement with similar appearance in the Pluto notebooks as the original Jupyter notebooks. I plan on refactoring the notebooks once I work through the remaining tutorials <sup>1</sup>.

The zeroth tutorial is not needed since Julia makes use of project toml files so once the repo is cloned the user just needs to activate the julia environment within the `pluto_notebooks` folder.

If there is no interest, no problem.

Thanks.

<sup>1</sup> For the neural network tutorial, Instead of using PyTorch I'm planning to  use  [FluxML.jl](https://fluxml.ai/Flux.jl/stable/)

### CODE REVIEW

**Comment by anthony-wang** [comment]
Hi @stefanbringuier, I'm sorry for the delay! This looks great, a Julia implementation is for sure welcome 😃 
Is this PR ready to merge as it is? Do you plan on adding the other notebooks as well, or should I review this PR as it is now?

**Comment by stefanbringuier** [comment]
@anthony-wang no worries for the delay.

> Is this PR ready to merge as it is?

For notebooks 1-3, yes.

> Do you plan on adding the other notebooks as well, or should I review this PR as it is now?

Yes, I will finish notebooks 4 and 5 soon just haven't had much time this last month.

**Review by anthony-wang — APPROVED** [review]
Looks good to me. Thanks!

**Comment by anthony-wang** [comment]
I've merged this PR as is, when you have the time to finish the rest of the notebooks, please let me know and I can merge that in a separate PR. Thanks 🙂

**Pull request merged**
